# -*- coding: utf-8 -*-
"""CreditCardFraud.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/127hQ6cqLt_Gxm3R_FcMwroCAJq7y978d

Import Dependencies
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load data set to panda dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv')

#first 5 row of data set
credit_card_data.head()

credit_card_data.tail()

#info data set
credit_card_data.info()

# or checking the missing values same as above
credit_card_data.isnull().sum()

